- name: Include distribution specific variables
  include_vars: "{{ lookup('first_found', params) }}"
  vars:
    params:
      files:
        - "{{ ansible_facts.os_family }}-{{ ansible_facts.distribution_major_version }}.yml"
        - "{{ ansible_facts.distribution }}-{{ ansible_facts.distribution_version }}.yml"
        - "{{ ansible_facts.os_family }}.yml"
        - "{{ ansible_facts.distribution }}.yml"
        - default.yml
      paths:
        - vars
  tags:
    - always
    - mongodb

- include_tasks: install-{{ ansible_facts.os_family }}.yml
  tags:
    - mongodb

- name: Copy mongod.conf
  template:
    src: mongod.conf.j2
    dest: "{{ mongodb_config_file }}"
    owner: root
    group: root
    mode: '0644'
  notify: restart mongodb
  tags:
    - mongodb
    - mongodb_config

- name: Copy logrotate config file
  template:
    src: logrotate_mongod.j2
    dest: /etc/logrotate.d/mongod
    owner: root
    group: root
    mode: '0644'
  tags:
    - mongodb
    - mongodb_config

- name: Start and enable mongo
  service:
    name: "{{ mongodb_service_name }}"
    enabled: yes
    state: started
  tags:
    - mongodb
    - mongodb_service
